-- V9__change_appointment_id_to_generated_by_default.sql

-- Change appointments.id from GENERATED ALWAYS AS IDENTITY to GENERATED BY DEFAULT AS IDENTITY
-- This allows manual ID insertion from external systems while maintaining auto-generation capability

-- Change the IDENTITY generation type from ALWAYS to BY DEFAULT
-- This allows manual ID insertion while still supporting auto-generation when ID is not provided
ALTER TABLE appointments
    ALTER COLUMN id SET GENERATED BY DEFAULT;

